name = "coast-fire-calculator"
main = "static/index.html"

[build]
  command = "echo 'No build needed for static site'"
  environment = "production"

[site]
  bucket = "static"

[env.production]
  name = "coast-fire-calculator-production"
  workers_dev = false
  route = "your-domain.com/*"

[build.upload]
  main = "static/index.html"
  format = "service-worker"

[build.upload.headers]
  "/static/*" = [
    "Cache-Control: max-age=31536000, public, immutable",
    "Pragma: public"
  ]
  "/fonts/*" = [
    "Cache-Control: max-age=31536000, public, immutable",
    "Pragma: public"
  ]
  "/chart.js" = [
    "Cache-Control: max-age=31536000, public, immutable",
    "Pragma: public"
  ]
  "/amp.html" = [
    "Cache-Control: max-age=31536000, public, immutable",
    "Pragma: public"
  ]
  "/amp.js" = [
    "Cache-Control: max-age=31536000, public, immutable",
    "Pragma: public"
  ]
  "/chart-config.json" = [
    "Cache-Control: max-age=31536000, public, immutable",
    "Pragma: public"
  ]
