name = "coast-fire-calculator"
type = "static"

[build]
  command = "echo 'No build needed for static site'"
  environment = "production"

[site]
  bucket = "static"
  entry-point = "static"

[env.production]
  name = "coast-fire-calculator-production"
  workers_dev = false
  route = "your-domain.com/*"

[build.upload]
  main = "static/index.html"
